/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/CardSolicitacoes.vue')['default']
    CardCirurgias: typeof import('./components/CardCirurgias.vue')['default']
    CardSolicitacoes: typeof import('./components/CardSolicitacoes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabelaDeSolicitacoes: typeof import('./components/TabelaDeSolicitacoesVirtual.vue')['default']
    TabelaDeSolicitacoesPaginada: typeof import('./components/TabelaDeSolicitacoesPaginada.vue')['default']
    TabelaDeSolicitacoesVirtual: typeof import('./components/TabelaDeSolicitacoesVirtual.vue')['default']
  }
}
